services:
  minio:
    image: minio/minio:latest
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
      MINIO_DOMAIN: s3.${DOMAIN}
    env_file: ./.env
    expose:
      - "9000"
      - "9001"
    volumes:
      - //e/s3:/data

  caddy:
    build:
      dockerfile: ./caddy/Dockerfile
      no_cache: true
    env_file: ./.env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro