services:
  minio:
    image: minio/minio:latest
    command: server --address ":9000" --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: ${MINIO_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET}
      MINIO_DOMAIN: s3.${DOMAIN}
    expose:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data

  caddy:
    restart: always
    build:
      dockerfile: ./caddy/Dockerfile
      no_cache: true
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - proxied
    volumes:
      - caddy_data:/data
    environment:
      EMAIL: ${EMAIL}
      DOMAIN: ${DOMAIN}
      CF_DNS_API_SECRET: ${CF_DNS_API_SECRET}

volumes:
  s3_data:
    driver: local
    driver_opts:
      type: none
      device: //e/s3
      o: bind
  caddy_data:

networks:
  public:
    name: public
    external: true
  proxied:
    name: proxied
    external: true
