name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  cleanup-deployments:
    name: Cleanup Deployment History
    runs-on: self-hosted
    environment: main

    steps:
      - name: Cleanup deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: main
          onlyRemoveDeployments: true

  deploy:
    runs-on: ubuntu-latest
    environment: main
    needs: ["cleanup-deployments"]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup .env
        run: |
          echo EMAIL=${{ secrets.EMAIL }} >> ./.env
          echo DOMAIN=${{ vars.DOMAIN }} >> ./.env
          echo CF_DNS_API_SECRET=${{ secrets.CF_DNS_API_SECRET }} >> ./.env
          echo MINIO_KEY=${{ vars.MINIO_KEY }} >> ./.env
          echo MINIO_SECRET=${{ secrets.MINIO_SECRET }} >> ./.env
          cat ./.env

      # - name: Deploy Stack
      #   uses: rouvenschandl/stack-deploy-action-cf-tunnel@v1.1
      #   with:
      #     name: desktop-infra
      #     mode: compose 
      #     file: ./compose.yaml
      #     host: ${{ vars.REMOTE_HOST }}
      #     user: ${{ vars.SSH_REMOTE_USER }}
      #     ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
      #     cf_service_token_id: ${{ secrets.CF_SERVICE_ID }}
      #     cf_service_token_secret: ${{ secrets.CF_SERVICE_SECRET }}
      #     env_file: ./.env
