name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  cleanup-deployments:
    name: Cleanup Deployment History
    runs-on: self-hosted
    environment: main

    steps:
      - name: Cleanup deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: main
          onlyRemoveDeployments: true

  deploy:
    runs-on: self-hosted
    environment: main
    needs: ["cleanup-deployments"]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup .env
        run: |
          echo EMAIL=${{ secrets.EMAIL }} >> ./.env
          echo DOMAIN=${{ vars.DOMAIN }} >> ./.env
          echo CF_DNS_API_SECRET=${{ secrets.CF_DNS_API_SECRET }} >> ./.env
          echo MINIO_KEY=${{ vars.MINIO_KEY }} >> ./.env
          echo MINIO_SECRET=${{ secrets.MINIO_SECRET }} >> ./.env
          cat ./.env

      # - name: Deploy Stack
      #   uses: cssnr/stack-deploy-action@v1.4
      #   with:
      #     name: desktop-infra
      #     mode: compose 
      #     file: ./compose.yaml
      #     host: unix:///var/run/docker.sock
      #     user: ${{ vars.SSH_REMOTE_USER }}
      #     ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
      #     env_file: ./.env

      - name: Setup Docker Compose
        uses: docker/docker-setup-compose@v1.2

      - name: Deploy Stack
        run: |
          docker compose up --remove-orphans --force-recreate
