name: Deploy
on:
  push:
    branches: ["main"]

jobs:
  cleanup-deployments:
    name: Cleanup Deployment History
    runs-on: self-hosted
    environment: main

    steps:
      - name: Cleanup deployments
        uses: strumwolf/delete-deployment-environment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: main
          onlyRemoveDeployments: true

  deploy:
    runs-on: self-hosted
    environment: main
    needs: ["cleanup-deployments"]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Docker Compose
        uses: docker/setup-compose-action@v1

      - name: Deploy Stack
        run: |
          docker compose up -d --remove-orphans --force-recreate
        env:
          EMAIL: ${{ secrets.EMAIL }}
          DOMAIN: ${{ vars.DOMAIN }}
          CF_DNS_API_SECRET: ${{ secrets.CF_DNS_API_SECRET }}
          MINIO_KEY: ${{ vars.MINIO_KEY }}
          MINIO_SECRET: ${{ secrets.MINIO_SECRET }}
